# Generated by Django 2.2.2 on 2019-06-07 11:14

from django.db import migrations

from ..utils import country_iso_codes
from ..models import Country


def migrate_countries(*args):
    Country.objects.bulk_create([Country(name=c[1], iso2=c[0], iso3=c[2], numeric=c[3]) for c in country_iso_codes])


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_countries)
    ]
