# Generated by Django 2.2.2 on 2019-07-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_auto_20190607_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='verification_status',
        ),
        migrations.AddField(
            model_name='user',
            name='is_dormant',
            field=models.BooleanField(default=False),
        ),
    ]
